### ISSUE TITLE
Motion detection broken while recording disabled

### ISSUE THREAD

**Issue by doug-hoffman** [AngellusMortis/pyunifiprotect#266]
After upgrading to HA 2023.2.x, motion entities are unavailable when recording is disabled. Motion entities work just fine while recording is disabled prior to this.

I see home-assistant/core#86329 bumped the pyunifiprotect dependency to change this behavior and attempt to avoid confusion where it wasn't working, but it seems the change took away functionality where it did previously work, as well.

The only instance when I've seen motion detection not work is when the privacy toggle is on in HA, due to the privacy mask, presumably.

Devices: G3 Flex, G4 Dome, G4 Doorbell
Protect version 2.7.18 on a UNVR with 3.0.16

**Comment by AngellusMortis** [comment]
This is expected behavior.

**Comment by doug-hoffman** [comment]
It worked fine with recording disabled until the behavior changed in pyunifiprotect. I don't want to record the interior of my house while anyone is home, but I do want motion events. I can't satisfy both requirements with the new behavior.

**Comment by AngellusMortis** [comment]
Then that is a problem you need to take up with the UniFi Protect devs. This library only implements things as they are provided by UniFi Protect. The functionality was fully changed in this library when it was confirmed that is the way it is was supposed to work from the devs. There is no support for tracking events for cameras when nothing is being recorded from them. Any functionality otherwise is a considered a bug.
