### ISSUE TITLE
Request: Enable feature to manage/control 'Share Livestream' option for camera

### ISSUE THREAD

**Issue by pqpxo** [AngellusMortis/pyunifiprotect#387]
Hello there!

Please let me know if there is a correct/proper place to raise this request.

Is there any possible chance of including a feature to manage/control the 'Share Livestream' feature for cameras within UniFi Protect.

I'd like to be able to enable/disable this feature (also provide the generated URL) within Home Assistant to include within my alarm system setup.

Many thanks!

**Comment by AngellusMortis** [comment]
This falls under "not going to be implement" list of features. No Remote Access features will ever be implemented by me.

https://github.com/AngellusMortis/pyunifiprotect?tab=readme-ov-file#remote-access--ubiquiti-cloud-features

**Comment by pqpxo** [comment]
No worries! I've been trying to conjure up something using scripts/cURL etc with no luck. Thanks anyway!

**Comment by AngellusMortis** [comment]
If you get it working, you are welcome to make a PR, but there is never any guarantee it will keep working in the future (you would need to maintain it). It looks like it is just a POST to `/sharedStream` for a camera object, but I have no idea if that is right since it just gives a 500 with Remote Access disabled.
